export const USER_SESSION_DURATION_MINUTES = 20;
export const USER_SESSION_DURATION_MS = USER_SESSION_DURATION_MINUTES * 60 * 1000;
export const USER_SESSION_DURATION_SECONDS = USER_SESSION_DURATION_MINUTES * 60;
export const USER_SESSION_COOKIE = 'user_session_expires_at';
