-- Migration: Seed detailed 2026 enforcement-fine violation rates
-- Created: 2026-06-11
-- Description: Expands grouped violation types into the detailed Building Act Enforcement Decree Attached Table 15 categories.

update public.enforcement_fine_violation_rates
set
  user_selectable = false,
  updated_at = now()
where year = 2026
  and code in (
    'other_building_act_violation_10',
    'other_violation_max_3'
  );

insert into public.enforcement_fine_violation_rates (
  year,
  code,
  label,
  formula_type,
  base_fine_rate,
  violation_rate,
  min_violation_rate,
  max_violation_rate,
  user_selectable,
  requires_local_ordinance,
  requires_user_confirmation,
  sort_order,
  description,
  source,
  source_detail
)
values
  (
    2026,
    'landscape_violation',
    '대지 조경 위반',
    'standard_value',
    null,
    0.1000,
    null,
    null,
    true,
    true,
    true,
    400,
    '건축법 제42조 대지의 조경에 관한 사항을 위반한 경우입니다. 위반부분 시가표준액에 10%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반5'
  ),
  (
    2026,
    'building_line_violation',
    '건축선 위반',
    'standard_value',
    null,
    0.1000,
    null,
    null,
    true,
    true,
    true,
    410,
    '건축법 제47조 건축선 기준에 적합하지 않은 경우입니다. 위반부분 시가표준액에 10%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반6'
  ),
  (
    2026,
    'structural_safety_violation',
    '구조내력 기준 위반',
    'standard_value',
    null,
    0.1000,
    null,
    null,
    true,
    true,
    true,
    420,
    '건축법 제48조 구조내력 기준에 적합하지 않은 경우입니다. 위반부분 시가표준액에 10%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반7'
  ),
  (
    2026,
    'evacuation_fire_compartment_violation',
    '피난·방화구획 등 기준 위반',
    'standard_value',
    null,
    0.1000,
    null,
    null,
    true,
    true,
    true,
    430,
    '건축법 제49조 피난시설, 용도·구조 제한, 방화구획, 계단, 거실 반자 높이, 채광·환기, 바닥 방습 등 기준 위반입니다. 위반부분 시가표준액에 10%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반8'
  ),
  (
    2026,
    'fire_resistant_wall_violation',
    '내화구조·방화벽 기준 위반',
    'standard_value',
    null,
    0.1000,
    null,
    null,
    true,
    true,
    true,
    440,
    '건축법 제50조 내화구조 및 방화벽 기준에 적합하지 않은 경우입니다. 위반부분 시가표준액에 10%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반9'
  ),
  (
    2026,
    'fire_district_violation',
    '방화지구 기준 위반',
    'standard_value',
    null,
    0.1000,
    null,
    null,
    true,
    true,
    true,
    450,
    '건축법 제51조 방화지구 안의 건축물 기준에 적합하지 않은 경우입니다. 위반부분 시가표준액에 10%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반10'
  ),
  (
    2026,
    'finish_material_violation',
    '마감재료 기준 위반',
    'standard_value',
    null,
    0.1000,
    null,
    null,
    true,
    true,
    true,
    460,
    '건축법 제52조 법령 등에 적합하지 않은 마감재료를 사용한 경우입니다. 위반부분 시가표준액에 10%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반11'
  ),
  (
    2026,
    'height_limit_violation',
    '높이 제한 위반',
    'standard_value',
    null,
    0.1000,
    null,
    null,
    true,
    true,
    true,
    470,
    '건축법 제60조 건축물 높이 제한을 위반한 경우입니다. 위반부분 시가표준액에 10%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반12'
  ),
  (
    2026,
    'sunlight_height_violation',
    '일조권 높이 제한 위반',
    'standard_value',
    null,
    0.1000,
    null,
    null,
    true,
    true,
    true,
    480,
    '건축법 제61조 일조 등의 확보를 위한 높이 제한을 위반한 경우입니다. 위반부분 시가표준액에 10%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반13'
  ),
  (
    2026,
    'building_equipment_violation',
    '건축설비 기준 위반',
    'standard_value',
    null,
    0.1000,
    null,
    null,
    true,
    true,
    true,
    490,
    '건축법 제62조 건축설비의 설치·구조 기준 및 설계·공사감리 관련 기준을 위반한 경우입니다. 위반부분 시가표준액에 10%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반14'
  ),
  (
    2026,
    'building_act_order_violation',
    '그 밖의 건축법령 위반',
    'standard_value',
    null,
    0.0300,
    null,
    null,
    true,
    true,
    true,
    990,
    '그 밖에 건축법 또는 건축법에 따른 명령이나 처분을 위반한 경우입니다. 위반부분 시가표준액에 3%를 적용합니다.',
    'https://www.law.go.kr/법령/건축법시행령/별표15',
    '건축법 시행령 별표 15 위반15'
  )
on conflict (year, code) do update set
  label = excluded.label,
  formula_type = excluded.formula_type,
  base_fine_rate = excluded.base_fine_rate,
  violation_rate = excluded.violation_rate,
  min_violation_rate = excluded.min_violation_rate,
  max_violation_rate = excluded.max_violation_rate,
  user_selectable = excluded.user_selectable,
  requires_local_ordinance = excluded.requires_local_ordinance,
  requires_user_confirmation = excluded.requires_user_confirmation,
  sort_order = excluded.sort_order,
  description = excluded.description,
  source = excluded.source,
  source_detail = excluded.source_detail,
  updated_at = now();
