-- Migration: Seed additional 2026 reduction special conditions
-- Created: 2026-06-11
-- Description: Adds missing official reduction/special-case candidates from the 2026 official calculator.

insert into public.enforcement_fine_special_condition_rates (
  year,
  code,
  label,
  condition_type,
  rate,
  multiplier,
  user_selectable,
  requires_user_confirmation,
  sort_order,
  description,
  source,
  source_detail
)
values
  (
    2026,
    'agriculture_fishery_facility_size_reduction',
    '농업·어업용 시설 규모 감경',
    'reduction',
    0.7500,
    0.2500,
    false,
    true,
    160,
    '축사 등 농업용·어업용 시설로서 500㎡ 이하인 경우, 수도권 외 지역은 1,000㎡ 이하인 경우 적용 가능성이 있는 감경 후보입니다. 시설 용도와 소재지 확인이 필요합니다.',
    'https://www.law.go.kr/법령/건축법시행령/제115조의4',
    '건축법 시행령 제115조의4 및 2026 공식 이행강제금 계산기 감경1'
  ),
  (
    2026,
    'tenant_correction_difficulty',
    '임차인 존재로 시정 곤란',
    'reduction',
    0.7500,
    0.2500,
    true,
    true,
    170,
    '임차인이 있어 현실적으로 임대기간 중 위반내용을 시정하기 어려운 경우 적용 가능성이 있는 감경 후보입니다. 최초 시정명령 전 임대차계약 여부와 계약 종료·갱신 여부 확인이 필요합니다.',
    'https://www.law.go.kr/법령/건축법시행령/제115조의4',
    '건축법 시행령 제115조의4 및 2026 공식 이행강제금 계산기 감경4'
  ),
  (
    2026,
    'existing_at_use_approval',
    '사용승인 당시 존재 위반',
    'reduction',
    0.7500,
    0.2500,
    true,
    true,
    180,
    '건축법 제22조에 따른 사용승인 당시 존재하던 위반사항이 사용승인 이후 확인된 경우 적용 가능성이 있는 감경 후보입니다. 건축물대장 변동사항 및 관할청 확인이 필요합니다.',
    'https://www.law.go.kr/법령/건축법시행령/제115조의4',
    '건축법 시행령 제115조의4 및 2026 공식 이행강제금 계산기 감경7'
  ),
  (
    2026,
    'livestock_excreta_permit_transition_1',
    '가축분뇨 배출시설 경과조치 감경',
    'reduction',
    0.7500,
    0.2500,
    false,
    true,
    190,
    '가축분뇨의 관리 및 이용에 관한 법률 일부개정법률 부칙상 경과조치 대상 배출시설인 경우 적용 가능성이 있는 감경 후보입니다.',
    'https://www.law.go.kr/법령/건축법시행령/제115조의4',
    '2026 공식 이행강제금 계산기 감경8'
  ),
  (
    2026,
    'livestock_excreta_permit_transition_2',
    '가축분뇨 허가신청 경과조치 감경',
    'reduction',
    0.7500,
    0.2500,
    false,
    true,
    200,
    '가축분뇨의 관리 및 이용에 관한 법률 일부개정법률 부칙상 기한까지 허가신청 또는 신고한 배출시설인 경우 적용 가능성이 있는 감경 후보입니다.',
    'https://www.law.go.kr/법령/건축법시행령/제115조의4',
    '2026 공식 이행강제금 계산기 감경9·감경10'
  ),
  (
    2026,
    'article80_use_without_approval_residential_half',
    '사용승인 미필 주거용',
    'reduction',
    0.5000,
    0.5000,
    false,
    true,
    210,
    '사용승인을 받지 아니하고 건축물을 사용한 주거용 건축물은 건축법 제80조 제1항 단서 및 조례에 따라 1/2 범위 특례 적용 가능성이 있습니다.',
    'https://www.law.go.kr/법령/건축법/제80조',
    '건축법 제80조 제1항 단서 및 2026 공식 이행강제금 계산기 특례2'
  ),
  (
    2026,
    'article80_landscape_residential_half',
    '조경 위반 주거용',
    'reduction',
    0.5000,
    0.5000,
    false,
    true,
    220,
    '대지의 조경에 관한 사항을 위반한 주거용 건축물은 건축법 제80조 제1항 단서 및 조례에 따라 1/2 범위 특례 적용 가능성이 있습니다.',
    'https://www.law.go.kr/법령/건축법/제80조',
    '건축법 제80조 제1항 단서 및 2026 공식 이행강제금 계산기 특례3'
  ),
  (
    2026,
    'article80_height_residential_half',
    '높이 제한 위반 주거용',
    'reduction',
    0.5000,
    0.5000,
    false,
    true,
    230,
    '건축물 높이 제한을 위반한 주거용 건축물은 건축법 제80조 제1항 단서 및 조례에 따라 1/2 범위 특례 적용 가능성이 있습니다.',
    'https://www.law.go.kr/법령/건축법/제80조',
    '건축법 제80조 제1항 단서 및 2026 공식 이행강제금 계산기 특례4'
  ),
  (
    2026,
    'article80_sunlight_residential_half',
    '일조사선 위반 주거용',
    'reduction',
    0.5000,
    0.5000,
    false,
    true,
    240,
    '일조 등의 확보를 위한 높이 제한을 위반한 주거용 건축물은 건축법 제80조 제1항 단서 및 조례에 따라 1/2 범위 특례 적용 가능성이 있습니다.',
    'https://www.law.go.kr/법령/건축법/제80조',
    '건축법 제80조 제1항 단서 및 2026 공식 이행강제금 계산기 특례5'
  ),
  (
    2026,
    'article80_ordinance_residential_half',
    '조례상 주거용 특례',
    'reduction',
    0.5000,
    0.5000,
    true,
    true,
    250,
    '그 밖의 건축조례로 정하는 주거용 위반사항은 건축법 제80조 제1항 단서 및 조례에 따라 1/2 범위 특례 적용 가능성이 있습니다.',
    'https://www.law.go.kr/법령/건축법/제80조',
    '건축법 제80조 제1항 단서 및 2026 공식 이행강제금 계산기 특례6'
  )
on conflict (year, code) do update set
  label = excluded.label,
  condition_type = excluded.condition_type,
  rate = excluded.rate,
  multiplier = excluded.multiplier,
  user_selectable = excluded.user_selectable,
  requires_user_confirmation = excluded.requires_user_confirmation,
  sort_order = excluded.sort_order,
  description = excluded.description,
  source = excluded.source,
  source_detail = excluded.source_detail,
  updated_at = now();
